// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SR_SoC-Display

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Ladeanzeige
void ui_Ladeanzeige_screen_init(void);
void ui_event_Ladeanzeige(lv_event_t * e);
lv_obj_t * ui_Ladeanzeige;
lv_obj_t * ui_Label_SoC_Value;
lv_obj_t * ui_Label_Time;
lv_obj_t * ui_Label_SoC_Unit;
lv_obj_t * ui_Label_km_Value;
lv_obj_t * ui_Label_km_Unit;
lv_obj_t * ui_AkkuLogo;
lv_obj_t * ui_Label_BattTemp_Value;
lv_obj_t * ui_SRLogo;
lv_obj_t * ui_Image_WLAN;
lv_obj_t * ui_Image_Shelly;
lv_obj_t * ui_Image_Error;
lv_obj_t * ui_Image_GO;
lv_obj_t * ui_Image_Brake;
lv_obj_t * ui_Image_HotSpot;
lv_obj_t * ui_Image_Achtung;
lv_obj_t * ui_Label_Threshold;
lv_obj_t * ui_Label_LoadPower;
lv_obj_t * ui_Label_LoadTempHigh;
// CUSTOM VARIABLES
lv_obj_t * uic_Ladeanzeige;
lv_obj_t * uic_Label_SoC_Value;
lv_obj_t * uic_Label_Time;
lv_obj_t * uic_Label_SoC_Unit;
lv_obj_t * uic_Label_km_Value;
lv_obj_t * uic_Label_km_Unit;
lv_obj_t * uic_AkkuLogo;
lv_obj_t * uic_Label_BattTemp_Value;
lv_obj_t * uic_SRLogo;
lv_obj_t * uic_Image_WLAN;
lv_obj_t * uic_Image_Shelly;
lv_obj_t * uic_Image_Error;
lv_obj_t * uic_Image_GO;
lv_obj_t * uic_Image_Brake;
lv_obj_t * uic_Image_HotSpot;
lv_obj_t * uic_Image_Achtung;
lv_obj_t * uic_Label_Threshold;
lv_obj_t * uic_Label_LoadPower;
lv_obj_t * uic_Label_LoadTempHigh;

// SCREEN: ui_Tacho
void ui_Tacho_screen_init(void);
void ui_event_Tacho(lv_event_t * e);
lv_obj_t * ui_Tacho;
lv_obj_t * ui_Label_Time_2;
lv_obj_t * ui_AkkuLogo_2;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Arc_Speed_2;
lv_obj_t * ui_Arc_Reku;
lv_obj_t * ui_ImageSkala;
lv_obj_t * ui_Label_SoC_Value_2;
lv_obj_t * ui_Label_SoC_Unit_2;
lv_obj_t * ui_Label_km_Value_2;
lv_obj_t * ui_Label_km_Unit_2;
lv_obj_t * ui_Label_BattTemp_Value2;
lv_obj_t * ui_Image_WLAN_2;
lv_obj_t * ui_Image_Shelly_2;
lv_obj_t * ui_Image_Error_2;
lv_obj_t * ui_Image_GO_2;
lv_obj_t * ui_Image_Brake_2;
lv_obj_t * ui_Image_HotSpot_2;
lv_obj_t * ui_Label_Speed_Value_2;
lv_obj_t * ui_Label_kmh_Unit_2;
lv_obj_t * ui_Zeiger;
lv_obj_t * ui_Image12;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label_LoadPower_2;
lv_obj_t * ui_Label_Threshold_2;
lv_obj_t * ui_Label_LoadTempHigh2;
lv_obj_t * ui_Image_Achtung2;
// CUSTOM VARIABLES
lv_obj_t * uic_Tacho;
lv_obj_t * uic_Label_Time_2;
lv_obj_t * uic_AkkuLogo_2;
lv_obj_t * uic_Arc_Speed_2;
lv_obj_t * uic_Arc_Reku;
lv_obj_t * uic_ImageSkala;
lv_obj_t * uic_Label_SoC_Value_2;
lv_obj_t * uic_Label_SoC_Unit_2;
lv_obj_t * uic_Label_km_Value_2;
lv_obj_t * uic_Label_km_Unit_2;
lv_obj_t * uic_Label_BattTemp_Value2;
lv_obj_t * uic_Image_WLAN_2;
lv_obj_t * uic_Image_Shelly_2;
lv_obj_t * uic_Image_Error_2;
lv_obj_t * uic_Image_GO_2;
lv_obj_t * uic_Image_Brake_2;
lv_obj_t * uic_Image_HotSpot_2;
lv_obj_t * uic_Label_Speed_Value_2;
lv_obj_t * uic_Label_kmh_Unit_2;
lv_obj_t * uic_Zeiger;
lv_obj_t * uic_Label_LoadPower_2;
lv_obj_t * uic_Label_Threshold_2;
lv_obj_t * uic_Label_LoadTempHigh2;
lv_obj_t * uic_Image_Achtung2;

// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
void ui_event_Settings(lv_event_t * e);
lv_obj_t * ui_Settings;
lv_obj_t * ui_PanelSteckdose;
void ui_event_Button_StartStop(lv_event_t * e);
lv_obj_t * ui_Button_StartStop;
lv_obj_t * ui_LabelSteckdose;
lv_obj_t * ui_LabelAUS;
lv_obj_t * ui_LabelEIN;
lv_obj_t * ui_PanelDarkmode;
void ui_event_SwitchDark(lv_event_t * e);
lv_obj_t * ui_SwitchDark;
lv_obj_t * ui_LabelDarkmode;
lv_obj_t * ui_PanelSoC;
lv_obj_t * ui_LabelSoC;
lv_obj_t * ui_SoCsetpoint;
// CUSTOM VARIABLES
lv_obj_t * uic_Settings;
lv_obj_t * uic_PanelSteckdose;
lv_obj_t * uic_Button_Start;
lv_obj_t * uic_LabelSteckdose;
lv_obj_t * uic_LabelAUS;
lv_obj_t * uic_LabelEIN;
lv_obj_t * uic_PanelDarkmode;
lv_obj_t * uic_SwitchDark;
lv_obj_t * uic_PanelSoC;
lv_obj_t * uic_LabelSoC;
lv_obj_t * uic_SoCsetpoint;

// SCREEN: ui_WiFiInfo
void ui_WiFiInfo_screen_init(void);
void ui_event_WiFiInfo(lv_event_t * e);
lv_obj_t * ui_WiFiInfo;
lv_obj_t * ui_PanelWiFi;
lv_obj_t * ui_Label_WiFi1;
lv_obj_t * ui_Label_WiFi2;
lv_obj_t * ui_Label_WiFi3;
lv_obj_t * ui_ImageWifi;
lv_obj_t * ui_PanelShelly;
lv_obj_t * ui_Label_Shelly1;
lv_obj_t * ui_Label_Shelly2;
lv_obj_t * ui_ImageShelly;
lv_obj_t * ui_PanelMQTT;
lv_obj_t * ui_Label_MQTT1;
lv_obj_t * ui_Label_MQTT2;
lv_obj_t * ui_ImageMQTT;
// CUSTOM VARIABLES
lv_obj_t * uic_WiFiInfo;
lv_obj_t * uic_PanelWiFi;
lv_obj_t * uic_Label_WiFi1;
lv_obj_t * uic_Label_WiFi2;
lv_obj_t * uic_Label_WiFi3;
lv_obj_t * uic_ImageWifi;
lv_obj_t * uic_Label_Shelly1;
lv_obj_t * uic_Label_Shelly2;
lv_obj_t * uic_ImageShelly;
lv_obj_t * uic_Label_MQTT1;
lv_obj_t * uic_Label_MQTT2;
lv_obj_t * uic_ImageMQTT;

// SCREEN: ui_SRInfo
void ui_SRInfo_screen_init(void);
void ui_event_SRInfo(lv_event_t * e);
lv_obj_t * ui_SRInfo;
lv_obj_t * ui_PanelConverter;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label_CtrlTemp;
lv_obj_t * ui_Label_limitSoC;
lv_obj_t * ui_Label_limitTemp;
lv_obj_t * ui_PanelBatt;
lv_obj_t * ui_Label_BattSoC;
lv_obj_t * ui_Label_BattVoltage;
lv_obj_t * ui_Label_BattCurrent;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label_BattMinTemp;
lv_obj_t * ui_Label_BattMaxTemp;
lv_obj_t * ui_Slider_Batterie;
lv_obj_t * ui_PanelMotor;
lv_obj_t * ui_Label_MotorTemp;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Panel_ChargerON;
lv_obj_t * ui_Label_ChargePower;
lv_obj_t * ui_PanelVersion;
lv_obj_t * ui_Label_SWversion;
lv_obj_t * ui_Label_HWversion;
lv_obj_t * ui_Label_DISPversion;
lv_obj_t * ui_PanelDistance;
lv_obj_t * ui_Label_totalDistance;
lv_obj_t * ui_Label_tripDistance;
lv_obj_t * ui_Label_km;
lv_obj_t * ui_Label_km1;
lv_obj_t * ui_Label_trip;
lv_obj_t * ui_Label_trip1;
// CUSTOM VARIABLES
lv_obj_t * uic_PanelConverter;
lv_obj_t * uic_Label_CtrlTemp;
lv_obj_t * uic_Label_limitSoC;
lv_obj_t * uic_Label_limitTemp;
lv_obj_t * uic_PanelBatt;
lv_obj_t * uic_Label_BattVoltage;
lv_obj_t * uic_Label_BattCurrent;
lv_obj_t * uic_Label_BattMinTemp;
lv_obj_t * uic_Label_BattMaxTemp;
lv_obj_t * uic_Slider_Batterie;
lv_obj_t * uic_Label_MotorTemp;
lv_obj_t * uic_Panel_ChargerON;
lv_obj_t * uic_Label_ChargePower;
lv_obj_t * uic_PanelVersion;
lv_obj_t * uic_Label_SWversion;
lv_obj_t * uic_Label_HWversion;
lv_obj_t * uic_Label_DISPversion;
lv_obj_t * uic_PanelDistance;
lv_obj_t * uic_Label_totalDistance;
lv_obj_t * uic_Label_tripDistance;
lv_obj_t * uic_Label_km;
lv_obj_t * uic_Label_trip;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Ladeanzeige(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Settings_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Tacho, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Tacho_screen_init);
    }
}

void ui_event_Tacho(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SRInfo, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_SRInfo_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Ladeanzeige, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Ladeanzeige_screen_init);
    }
}

void ui_event_Settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_WiFiInfo, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_WiFiInfo_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Ladeanzeige, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Ladeanzeige_screen_init);
    }
}

void ui_event_Button_StartStop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        StartStopPlug(e);
    }
}

void ui_event_SwitchDark(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_DEFAULT);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_DARKMODE);
    }
}

void ui_event_WiFiInfo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SRInfo, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_SRInfo_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Settings_screen_init);
    }
}

void ui_event_SRInfo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Tacho, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Tacho_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_WiFiInfo, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_WiFiInfo_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Ladeanzeige_screen_init();
    ui_Tacho_screen_init();
    ui_Settings_screen_init();
    ui_WiFiInfo_screen_init();
    ui_SRInfo_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Ladeanzeige);
}
