// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SR_SoC-Display

#ifndef _SR_SOC_DISPLAY_UI_H
#define _SR_SOC_DISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_Ladeanzeige
void ui_Ladeanzeige_screen_init(void);
void ui_event_Ladeanzeige(lv_event_t * e);
extern lv_obj_t * ui_Ladeanzeige;
extern lv_obj_t * ui_Label_SoC_Value;
extern lv_obj_t * ui_Label_Time;
extern lv_obj_t * ui_Label_SoC_Unit;
extern lv_obj_t * ui_Label_km_Value;
extern lv_obj_t * ui_Label_km_Unit;
extern lv_obj_t * ui_AkkuLogo;
extern lv_obj_t * ui_Label_BattTemp_Value;
extern lv_obj_t * ui_SRLogo;
extern lv_obj_t * ui_Image_WLAN;
extern lv_obj_t * ui_Image_Shelly;
extern lv_obj_t * ui_Image_Error;
extern lv_obj_t * ui_Image_GO;
extern lv_obj_t * ui_Image_Brake;
extern lv_obj_t * ui_Image_HotSpot;
extern lv_obj_t * ui_Image_Achtung;
extern lv_obj_t * ui_Label_Threshold;
extern lv_obj_t * ui_Label_LoadPower;
extern lv_obj_t * ui_Label_LoadTempHigh;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Ladeanzeige;
extern lv_obj_t * uic_Label_SoC_Value;
extern lv_obj_t * uic_Label_Time;
extern lv_obj_t * uic_Label_SoC_Unit;
extern lv_obj_t * uic_Label_km_Value;
extern lv_obj_t * uic_Label_km_Unit;
extern lv_obj_t * uic_AkkuLogo;
extern lv_obj_t * uic_Label_BattTemp_Value;
extern lv_obj_t * uic_SRLogo;
extern lv_obj_t * uic_Image_WLAN;
extern lv_obj_t * uic_Image_Shelly;
extern lv_obj_t * uic_Image_Error;
extern lv_obj_t * uic_Image_GO;
extern lv_obj_t * uic_Image_Brake;
extern lv_obj_t * uic_Image_HotSpot;
extern lv_obj_t * uic_Image_Achtung;
extern lv_obj_t * uic_Label_Threshold;
extern lv_obj_t * uic_Label_LoadPower;
extern lv_obj_t * uic_Label_LoadTempHigh;

// SCREEN: ui_Tacho
void ui_Tacho_screen_init(void);
void ui_event_Tacho(lv_event_t * e);
extern lv_obj_t * ui_Tacho;
extern lv_obj_t * ui_Label_Time_2;
extern lv_obj_t * ui_AkkuLogo_2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Arc_Speed_2;
extern lv_obj_t * ui_Arc_Reku;
extern lv_obj_t * ui_ImageSkala;
extern lv_obj_t * ui_Label_SoC_Value_2;
extern lv_obj_t * ui_Label_SoC_Unit_2;
extern lv_obj_t * ui_Label_km_Value_2;
extern lv_obj_t * ui_Label_km_Unit_2;
extern lv_obj_t * ui_Label_BattTemp_Value2;
extern lv_obj_t * ui_Image_WLAN_2;
extern lv_obj_t * ui_Image_Shelly_2;
extern lv_obj_t * ui_Image_Error_2;
extern lv_obj_t * ui_Image_GO_2;
extern lv_obj_t * ui_Image_Brake_2;
extern lv_obj_t * ui_Image_HotSpot_2;
extern lv_obj_t * ui_Label_Speed_Value_2;
extern lv_obj_t * ui_Label_kmh_Unit_2;
extern lv_obj_t * ui_Zeiger;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label_LoadPower_2;
extern lv_obj_t * ui_Label_Threshold_2;
extern lv_obj_t * ui_Label_LoadTempHigh2;
extern lv_obj_t * ui_Image_Achtung2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Tacho;
extern lv_obj_t * uic_Label_Time_2;
extern lv_obj_t * uic_AkkuLogo_2;
extern lv_obj_t * uic_Arc_Speed_2;
extern lv_obj_t * uic_Arc_Reku;
extern lv_obj_t * uic_ImageSkala;
extern lv_obj_t * uic_Label_SoC_Value_2;
extern lv_obj_t * uic_Label_SoC_Unit_2;
extern lv_obj_t * uic_Label_km_Value_2;
extern lv_obj_t * uic_Label_km_Unit_2;
extern lv_obj_t * uic_Label_BattTemp_Value2;
extern lv_obj_t * uic_Image_WLAN_2;
extern lv_obj_t * uic_Image_Shelly_2;
extern lv_obj_t * uic_Image_Error_2;
extern lv_obj_t * uic_Image_GO_2;
extern lv_obj_t * uic_Image_Brake_2;
extern lv_obj_t * uic_Image_HotSpot_2;
extern lv_obj_t * uic_Label_Speed_Value_2;
extern lv_obj_t * uic_Label_kmh_Unit_2;
extern lv_obj_t * uic_Zeiger;
extern lv_obj_t * uic_Label_LoadPower_2;
extern lv_obj_t * uic_Label_Threshold_2;
extern lv_obj_t * uic_Label_LoadTempHigh2;
extern lv_obj_t * uic_Image_Achtung2;

// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
void ui_event_Settings(lv_event_t * e);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_PanelSteckdose;
void ui_event_Button_StartStop(lv_event_t * e);
extern lv_obj_t * ui_Button_StartStop;
extern lv_obj_t * ui_LabelSteckdose;
extern lv_obj_t * ui_LabelAUS;
extern lv_obj_t * ui_LabelEIN;
extern lv_obj_t * ui_PanelDarkmode;
void ui_event_SwitchDark(lv_event_t * e);
extern lv_obj_t * ui_SwitchDark;
extern lv_obj_t * ui_LabelDarkmode;
extern lv_obj_t * ui_PanelSoC;
extern lv_obj_t * ui_LabelSoC;
extern lv_obj_t * ui_SoCsetpoint;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Settings;
extern lv_obj_t * uic_PanelSteckdose;
extern lv_obj_t * uic_Button_Start;
extern lv_obj_t * uic_LabelSteckdose;
extern lv_obj_t * uic_LabelAUS;
extern lv_obj_t * uic_LabelEIN;
extern lv_obj_t * uic_PanelDarkmode;
extern lv_obj_t * uic_SwitchDark;
extern lv_obj_t * uic_PanelSoC;
extern lv_obj_t * uic_LabelSoC;
extern lv_obj_t * uic_SoCsetpoint;

// SCREEN: ui_WiFiInfo
void ui_WiFiInfo_screen_init(void);
void ui_event_WiFiInfo(lv_event_t * e);
extern lv_obj_t * ui_WiFiInfo;
extern lv_obj_t * ui_PanelWiFi;
extern lv_obj_t * ui_Label_WiFi1;
extern lv_obj_t * ui_Label_WiFi2;
extern lv_obj_t * ui_Label_WiFi3;
extern lv_obj_t * ui_ImageWifi;
extern lv_obj_t * ui_PanelShelly;
extern lv_obj_t * ui_Label_Shelly1;
extern lv_obj_t * ui_Label_Shelly2;
extern lv_obj_t * ui_ImageShelly;
extern lv_obj_t * ui_PanelMQTT;
extern lv_obj_t * ui_Label_MQTT1;
extern lv_obj_t * ui_Label_MQTT2;
extern lv_obj_t * ui_ImageMQTT;
// CUSTOM VARIABLES
extern lv_obj_t * uic_WiFiInfo;
extern lv_obj_t * uic_PanelWiFi;
extern lv_obj_t * uic_Label_WiFi1;
extern lv_obj_t * uic_Label_WiFi2;
extern lv_obj_t * uic_Label_WiFi3;
extern lv_obj_t * uic_ImageWifi;
extern lv_obj_t * uic_Label_Shelly1;
extern lv_obj_t * uic_Label_Shelly2;
extern lv_obj_t * uic_ImageShelly;
extern lv_obj_t * uic_Label_MQTT1;
extern lv_obj_t * uic_Label_MQTT2;
extern lv_obj_t * uic_ImageMQTT;

// SCREEN: ui_SRInfo
void ui_SRInfo_screen_init(void);
void ui_event_SRInfo(lv_event_t * e);
extern lv_obj_t * ui_SRInfo;
extern lv_obj_t * ui_PanelConverter;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label_CtrlTemp;
extern lv_obj_t * ui_Label_limitSoC;
extern lv_obj_t * ui_Label_limitTemp;
extern lv_obj_t * ui_PanelBatt;
extern lv_obj_t * ui_Label_BattSoC;
extern lv_obj_t * ui_Label_BattVoltage;
extern lv_obj_t * ui_Label_BattCurrent;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label_BattMinTemp;
extern lv_obj_t * ui_Label_BattMaxTemp;
extern lv_obj_t * ui_Slider_Batterie;
extern lv_obj_t * ui_PanelMotor;
extern lv_obj_t * ui_Label_MotorTemp;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Panel_ChargerON;
extern lv_obj_t * ui_Label_ChargePower;
extern lv_obj_t * ui_PanelVersion;
extern lv_obj_t * ui_Label_SWversion;
extern lv_obj_t * ui_Label_HWversion;
extern lv_obj_t * ui_Label_DISPversion;
extern lv_obj_t * ui_PanelDistance;
extern lv_obj_t * ui_Label_totalDistance;
extern lv_obj_t * ui_Label_tripDistance;
extern lv_obj_t * ui_Label_km;
extern lv_obj_t * ui_Label_km1;
extern lv_obj_t * ui_Label_trip;
extern lv_obj_t * ui_Label_trip1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_PanelConverter;
extern lv_obj_t * uic_Label_CtrlTemp;
extern lv_obj_t * uic_Label_limitSoC;
extern lv_obj_t * uic_Label_limitTemp;
extern lv_obj_t * uic_PanelBatt;
extern lv_obj_t * uic_Label_BattVoltage;
extern lv_obj_t * uic_Label_BattCurrent;
extern lv_obj_t * uic_Label_BattMinTemp;
extern lv_obj_t * uic_Label_BattMaxTemp;
extern lv_obj_t * uic_Slider_Batterie;
extern lv_obj_t * uic_Label_MotorTemp;
extern lv_obj_t * uic_Panel_ChargerON;
extern lv_obj_t * uic_Label_ChargePower;
extern lv_obj_t * uic_PanelVersion;
extern lv_obj_t * uic_Label_SWversion;
extern lv_obj_t * uic_Label_HWversion;
extern lv_obj_t * uic_Label_DISPversion;
extern lv_obj_t * uic_PanelDistance;
extern lv_obj_t * uic_Label_totalDistance;
extern lv_obj_t * uic_Label_tripDistance;
extern lv_obj_t * uic_Label_km;
extern lv_obj_t * uic_Label_trip;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_secondride_logows_bar_png);    // assets/SecondRide_LogoWS_Bar.png
LV_IMG_DECLARE(ui_img_secondride_logosw_png);    // assets/SecondRide_LogoSW.png
LV_IMG_DECLARE(ui_img_1767220752);    // assets/icons8-wi-fi-verbunden-50.png
LV_IMG_DECLARE(ui_img_602373867);    // assets/icons8-steckdose-50.png
LV_IMG_DECLARE(ui_img_133863867);    // assets/icons8-fehler-64.png
LV_IMG_DECLARE(ui_img_1435283132);    // assets/icons8-gehen-64.png
LV_IMG_DECLARE(ui_img_400979676);    // assets/icons8-bremsenwarnung-65.png
LV_IMG_DECLARE(ui_img_517647767);    // assets/hotspot-64.png
LV_IMG_DECLARE(ui_img_secondride_logows_bar_klein_png);    // assets/SecondRide_LogoWS_Bar_klein.png
LV_IMG_DECLARE(ui_img_secondride_logows_klein_png);    // assets/SecondRide_LogoWS_klein.png
LV_IMG_DECLARE(ui_img_tachoskala_png);    // assets/TachoSkala.png
LV_IMG_DECLARE(ui_img_zeiger2_png);    // assets/Zeiger2.png
LV_IMG_DECLARE(ui_img_strich_kurz_png);    // assets/Strich_kurz.png
LV_IMG_DECLARE(ui_img_374202920);    // assets/icons8-wi-fi-logo-100.png
LV_IMG_DECLARE(ui_img_798314644);    // assets/shelly-white.png
LV_IMG_DECLARE(ui_img_1045174431);    // assets/Mqtt-hor.svg.png
LV_IMG_DECLARE(ui_img_1569223354);    // assets/icons8-batterie-100.png
LV_IMG_DECLARE(ui_img_secondride_diagnose_png);    // assets/SecondRide_Diagnose.png

// FONTS
LV_FONT_DECLARE(ui_font_ArialBig);
LV_FONT_DECLARE(ui_font_ArialMed);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
