// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SR_SoC-Display

#include "ui.h"

void ui_Ladeanzeige_screen_init(void)
{
    ui_Ladeanzeige = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Ladeanzeige, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Ladeanzeige, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackColor);
    ui_object_set_themeable_style_property(ui_Ladeanzeige, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackColor);

    ui_Label_SoC_Value = lv_label_create(ui_Ladeanzeige);
    lv_obj_set_width(ui_Label_SoC_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_SoC_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_SoC_Value, -283);
    lv_obj_set_y(ui_Label_SoC_Value, 149);
    lv_obj_set_align(ui_Label_SoC_Value, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_SoC_Value, "100");
    ui_object_set_themeable_style_property(ui_Label_SoC_Value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_SoC_Value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_SoC_Value, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_SoC_Value, &ui_font_ArialMed, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Time = lv_label_create(ui_Ladeanzeige);
    lv_obj_set_width(ui_Label_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Time, -163);
    lv_obj_set_y(ui_Label_Time, -202);
    lv_obj_set_align(ui_Label_Time, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_Time, "00:00");
    ui_object_set_themeable_style_property(ui_Label_Time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_Time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_Time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Time, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_SoC_Unit = lv_label_create(ui_Ladeanzeige);
    lv_obj_set_width(ui_Label_SoC_Unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_SoC_Unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_SoC_Unit, -38);
    lv_obj_set_y(ui_Label_SoC_Unit, 159);
    lv_obj_set_align(ui_Label_SoC_Unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_SoC_Unit, "%");
    ui_object_set_themeable_style_property(ui_Label_SoC_Unit, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_SoC_Unit, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_font(ui_Label_SoC_Unit, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_km_Value = lv_label_create(ui_Ladeanzeige);
    lv_obj_set_width(ui_Label_km_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_km_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_km_Value, -129);
    lv_obj_set_y(ui_Label_km_Value, 149);
    lv_obj_set_align(ui_Label_km_Value, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_km_Value, "70");
    ui_object_set_themeable_style_property(ui_Label_km_Value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_km_Value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_km_Value, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_km_Value, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_km_Unit = lv_label_create(ui_Ladeanzeige);
    lv_obj_set_width(ui_Label_km_Unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_km_Unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_km_Unit, 130);
    lv_obj_set_y(ui_Label_km_Unit, 156);
    lv_obj_set_align(ui_Label_km_Unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_km_Unit, "km");
    ui_object_set_themeable_style_property(ui_Label_km_Unit, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_km_Unit, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_font(ui_Label_km_Unit, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AkkuLogo = lv_slider_create(ui_Ladeanzeige);
    lv_slider_set_range(ui_AkkuLogo, -28, 135);
    lv_slider_set_value(ui_AkkuLogo, 75, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_AkkuLogo) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_AkkuLogo, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_AkkuLogo, 307);
    lv_obj_set_height(ui_AkkuLogo, 502);
    lv_obj_set_x(ui_AkkuLogo, 57);
    lv_obj_set_y(ui_AkkuLogo, 10);
    lv_obj_set_align(ui_AkkuLogo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AkkuLogo, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AkkuLogo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AkkuLogo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_AkkuLogo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_AkkuLogo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_AkkuLogo, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AkkuLogo, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AkkuLogo, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_AkkuLogo, &ui_img_secondride_logows_bar_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_AkkuLogo, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AkkuLogo, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label_BattTemp_Value = lv_label_create(ui_Ladeanzeige);
    lv_obj_set_width(ui_Label_BattTemp_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_BattTemp_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_BattTemp_Value, -241);
    lv_obj_set_y(ui_Label_BattTemp_Value, 73);
    lv_obj_set_align(ui_Label_BattTemp_Value, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_BattTemp_Value, "44°C");
    ui_object_set_themeable_style_property(ui_Label_BattTemp_Value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_BattTemp_Value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_BattTemp_Value, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_BattTemp_Value, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label_BattTemp_Value, lv_color_hex(0xEE8D00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label_BattTemp_Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SRLogo = lv_img_create(ui_Ladeanzeige);
    lv_img_set_src(ui_SRLogo, &ui_img_secondride_logosw_png);
    lv_obj_set_width(ui_SRLogo, LV_SIZE_CONTENT);   /// 466
    lv_obj_set_height(ui_SRLogo, LV_SIZE_CONTENT);    /// 466
    lv_obj_set_x(ui_SRLogo, -24);
    lv_obj_set_y(ui_SRLogo, 11);
    lv_obj_set_align(ui_SRLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SRLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SRLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SRLogo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_SRLogo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_Image_WLAN = lv_img_create(ui_Ladeanzeige);
    lv_img_set_src(ui_Image_WLAN, &ui_img_1767220752);
    lv_obj_set_width(ui_Image_WLAN, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image_WLAN, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image_WLAN, 201);
    lv_obj_set_y(ui_Image_WLAN, -33);
    lv_obj_set_align(ui_Image_WLAN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_WLAN, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_WLAN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image_WLAN, 180);
    ui_object_set_themeable_style_property(ui_Image_WLAN, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Image_WLAN, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_Image_Shelly = lv_img_create(ui_Ladeanzeige);
    lv_img_set_src(ui_Image_Shelly, &ui_img_602373867);
    lv_obj_set_width(ui_Image_Shelly, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image_Shelly, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image_Shelly, 203);
    lv_obj_set_y(ui_Image_Shelly, 11);
    lv_obj_set_align(ui_Image_Shelly, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Shelly, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Shelly, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image_Shelly, 180);
    ui_object_set_themeable_style_property(ui_Image_Shelly, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Image_Shelly, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_Image_Error = lv_img_create(ui_Ladeanzeige);
    lv_img_set_src(ui_Image_Error, &ui_img_133863867);
    lv_obj_set_width(ui_Image_Error, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image_Error, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image_Error, 172);
    lv_obj_set_y(ui_Image_Error, 96);
    lv_obj_set_align(ui_Image_Error, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Error, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Error, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image_Error, 200);
    lv_obj_set_style_img_recolor(ui_Image_Error, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image_Error, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_GO = lv_img_create(ui_Ladeanzeige);
    lv_img_set_src(ui_Image_GO, &ui_img_1435283132);
    lv_obj_set_width(ui_Image_GO, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image_GO, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image_GO, 172);
    lv_obj_set_y(ui_Image_GO, 99);
    lv_obj_set_align(ui_Image_GO, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_GO, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_GO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image_GO, 180);
    lv_obj_set_style_img_recolor(ui_Image_GO, lv_color_hex(0x055102), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image_GO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_Brake = lv_img_create(ui_Ladeanzeige);
    lv_img_set_src(ui_Image_Brake, &ui_img_400979676);
    lv_obj_set_width(ui_Image_Brake, LV_SIZE_CONTENT);   /// 65
    lv_obj_set_height(ui_Image_Brake, LV_SIZE_CONTENT);    /// 65
    lv_obj_set_x(ui_Image_Brake, 190);
    lv_obj_set_y(ui_Image_Brake, 52);
    lv_obj_set_align(ui_Image_Brake, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Brake, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Brake, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image_Brake, 180);
    lv_obj_set_style_img_recolor(ui_Image_Brake, lv_color_hex(0xEC7213), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image_Brake, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_HotSpot = lv_img_create(ui_Ladeanzeige);
    lv_img_set_src(ui_Image_HotSpot, &ui_img_517647767);
    lv_obj_set_width(ui_Image_HotSpot, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image_HotSpot, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image_HotSpot, 203);
    lv_obj_set_y(ui_Image_HotSpot, -32);
    lv_obj_set_align(ui_Image_HotSpot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_HotSpot, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_HotSpot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image_HotSpot, 180);
    ui_object_set_themeable_style_property(ui_Image_HotSpot, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Image_HotSpot, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_Image_Achtung = lv_img_create(ui_Ladeanzeige);
    lv_img_set_src(ui_Image_Achtung, &ui_img_133863867);
    lv_obj_set_width(ui_Image_Achtung, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image_Achtung, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image_Achtung, 98);
    lv_obj_set_y(ui_Image_Achtung, -54);
    lv_obj_set_align(ui_Image_Achtung, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Achtung, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Achtung, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Image_Achtung, lv_color_hex(0xEE8C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image_Achtung, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Threshold = lv_label_create(ui_Ladeanzeige);
    lv_obj_set_width(ui_Label_Threshold, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Threshold, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Threshold, 30);
    lv_obj_set_y(ui_Label_Threshold, 30);
    lv_obj_set_align(ui_Label_Threshold, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Threshold, "bis 80%");
    lv_obj_set_style_text_color(ui_Label_Threshold, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Threshold, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Threshold, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Threshold, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label_Threshold, lv_color_hex(0x00A1EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label_Threshold, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label_Threshold, lv_color_hex(0x00A1EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label_Threshold, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label_Threshold, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_LoadPower = lv_label_create(ui_Ladeanzeige);
    lv_obj_set_width(ui_Label_LoadPower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_LoadPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_LoadPower, 30);
    lv_obj_set_y(ui_Label_LoadPower, -5);
    lv_obj_set_align(ui_Label_LoadPower, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_LoadPower, "Wird geladen mit 1000W");
    lv_obj_set_style_text_color(ui_Label_LoadPower, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_LoadPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_LoadPower, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label_LoadPower, lv_color_hex(0x00A1EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label_LoadPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label_LoadPower, lv_color_hex(0x00A1EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label_LoadPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label_LoadPower, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_LoadTempHigh = lv_label_create(ui_Ladeanzeige);
    lv_obj_set_width(ui_Label_LoadTempHigh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_LoadTempHigh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_LoadTempHigh, 30);
    lv_obj_set_y(ui_Label_LoadTempHigh, -40);
    lv_obj_set_align(ui_Label_LoadTempHigh, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_LoadTempHigh, "Akkutemperatur zu hoch");
    lv_obj_set_style_text_color(ui_Label_LoadTempHigh, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_LoadTempHigh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_LoadTempHigh, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label_LoadTempHigh, lv_color_hex(0xEE8C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label_LoadTempHigh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label_LoadTempHigh, lv_color_hex(0xEE8C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label_LoadTempHigh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label_LoadTempHigh, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Ladeanzeige, ui_event_Ladeanzeige, LV_EVENT_ALL, NULL);
    uic_Ladeanzeige = ui_Ladeanzeige;
    uic_Label_SoC_Value = ui_Label_SoC_Value;
    uic_Label_Time = ui_Label_Time;
    uic_Label_SoC_Unit = ui_Label_SoC_Unit;
    uic_Label_km_Value = ui_Label_km_Value;
    uic_Label_km_Unit = ui_Label_km_Unit;
    uic_AkkuLogo = ui_AkkuLogo;
    uic_Label_BattTemp_Value = ui_Label_BattTemp_Value;
    uic_SRLogo = ui_SRLogo;
    uic_Image_WLAN = ui_Image_WLAN;
    uic_Image_Shelly = ui_Image_Shelly;
    uic_Image_Error = ui_Image_Error;
    uic_Image_GO = ui_Image_GO;
    uic_Image_Brake = ui_Image_Brake;
    uic_Image_HotSpot = ui_Image_HotSpot;
    uic_Image_Achtung = ui_Image_Achtung;
    uic_Label_Threshold = ui_Label_Threshold;
    uic_Label_LoadPower = ui_Label_LoadPower;
    uic_Label_LoadTempHigh = ui_Label_LoadTempHigh;

}
