// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SR_SoC-Display

#include "ui.h"

void ui_SRInfo_screen_init(void)
{
    ui_SRInfo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SRInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SRInfo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackColor);
    ui_object_set_themeable_style_property(ui_SRInfo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackColor);

    ui_PanelConverter = lv_obj_create(ui_SRInfo);
    lv_obj_set_width(ui_PanelConverter, 313);
    lv_obj_set_height(ui_PanelConverter, 91);
    lv_obj_set_x(ui_PanelConverter, 101);
    lv_obj_set_y(ui_PanelConverter, -9);
    lv_obj_set_align(ui_PanelConverter, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelConverter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelConverter, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PanelConverter, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelConverter, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelConverter, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_PanelConverter, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_Label8 = lv_label_create(ui_PanelConverter);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, -26);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "limit SOC");
    ui_object_set_themeable_style_property(ui_Label8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label8, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_PanelConverter);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -5);
    lv_obj_set_y(ui_Label9, 30);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "limit Temp");
    ui_object_set_themeable_style_property(ui_Label9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_CtrlTemp = lv_label_create(ui_PanelConverter);
    lv_obj_set_width(ui_Label_CtrlTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_CtrlTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_CtrlTemp, -14);
    lv_obj_set_y(ui_Label_CtrlTemp, 1);
    lv_obj_set_align(ui_Label_CtrlTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_CtrlTemp, "22°C");
    ui_object_set_themeable_style_property(ui_Label_CtrlTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_CtrlTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_CtrlTemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_CtrlTemp, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_limitSoC = lv_label_create(ui_PanelConverter);
    lv_obj_set_width(ui_Label_limitSoC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_limitSoC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_limitSoC, 85);
    lv_obj_set_y(ui_Label_limitSoC, -27);
    lv_obj_set_align(ui_Label_limitSoC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_limitSoC, "100%");
    ui_object_set_themeable_style_property(ui_Label_limitSoC, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_limitSoC, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_limitSoC, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_limitSoC, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_limitTemp = lv_label_create(ui_PanelConverter);
    lv_obj_set_width(ui_Label_limitTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_limitTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_limitTemp, 86);
    lv_obj_set_y(ui_Label_limitTemp, 29);
    lv_obj_set_align(ui_Label_limitTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_limitTemp, "100%");
    ui_object_set_themeable_style_property(ui_Label_limitTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_limitTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_limitTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_limitTemp, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBatt = lv_obj_create(ui_SRInfo);
    lv_obj_set_width(ui_PanelBatt, 313);
    lv_obj_set_height(ui_PanelBatt, 145);
    lv_obj_set_x(ui_PanelBatt, 8);
    lv_obj_set_y(ui_PanelBatt, -187);
    lv_obj_set_align(ui_PanelBatt, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelBatt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelBatt, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PanelBatt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelBatt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelBatt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_PanelBatt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_Label_BattSoC = lv_label_create(ui_PanelBatt);
    lv_obj_set_width(ui_Label_BattSoC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_BattSoC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_BattSoC, -8);
    lv_obj_set_y(ui_Label_BattSoC, -24);
    lv_obj_set_align(ui_Label_BattSoC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_BattSoC, "100%");
    ui_object_set_themeable_style_property(ui_Label_BattSoC, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_BattSoC, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_BattSoC, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_BattSoC, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_BattVoltage = lv_label_create(ui_PanelBatt);
    lv_obj_set_width(ui_Label_BattVoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_BattVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_BattVoltage, -85);
    lv_obj_set_y(ui_Label_BattVoltage, 5);
    lv_obj_set_align(ui_Label_BattVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_BattVoltage, "50V");
    ui_object_set_themeable_style_property(ui_Label_BattVoltage, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_BattVoltage, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_BattVoltage, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_BattVoltage, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_BattCurrent = lv_label_create(ui_PanelBatt);
    lv_obj_set_width(ui_Label_BattCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_BattCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_BattCurrent, -85);
    lv_obj_set_y(ui_Label_BattCurrent, 36);
    lv_obj_set_align(ui_Label_BattCurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_BattCurrent, "0.1A");
    ui_object_set_themeable_style_property(ui_Label_BattCurrent, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_BattCurrent, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_BattCurrent, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_BattCurrent, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_PanelBatt);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 64);
    lv_obj_set_y(ui_Label7, 23);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "min");
    ui_object_set_themeable_style_property(ui_Label7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_PanelBatt);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 62);
    lv_obj_set_y(ui_Label6, 49);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "max");
    ui_object_set_themeable_style_property(ui_Label6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_BattMinTemp = lv_label_create(ui_PanelBatt);
    lv_obj_set_width(ui_Label_BattMinTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_BattMinTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_BattMinTemp, 115);
    lv_obj_set_y(ui_Label_BattMinTemp, 24);
    lv_obj_set_align(ui_Label_BattMinTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_BattMinTemp, "22°C");
    ui_object_set_themeable_style_property(ui_Label_BattMinTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_BattMinTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_BattMinTemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_BattMinTemp, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_BattMaxTemp = lv_label_create(ui_PanelBatt);
    lv_obj_set_width(ui_Label_BattMaxTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_BattMaxTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_BattMaxTemp, 116);
    lv_obj_set_y(ui_Label_BattMaxTemp, 50);
    lv_obj_set_align(ui_Label_BattMaxTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_BattMaxTemp, "22°C");
    ui_object_set_themeable_style_property(ui_Label_BattMaxTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_BattMaxTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_BattMaxTemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_BattMaxTemp, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider_Batterie = lv_slider_create(ui_SRInfo);
    lv_slider_set_range(ui_Slider_Batterie, -11, 108);
    lv_slider_set_value(ui_Slider_Batterie, 199, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider_Batterie) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider_Batterie, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider_Batterie, 100);
    lv_obj_set_height(ui_Slider_Batterie, 64);
    lv_obj_set_x(ui_Slider_Batterie, 2);
    lv_obj_set_y(ui_Slider_Batterie, -167);
    lv_obj_set_align(ui_Slider_Batterie, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Slider_Batterie, LV_STATE_DISABLED);       /// States
    lv_obj_set_style_bg_color(ui_Slider_Batterie, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_Batterie, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider_Batterie, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider_Batterie, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_Batterie, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider_Batterie, &ui_img_1569223354, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider_Batterie, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider_Batterie, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_PanelMotor = lv_obj_create(ui_SRInfo);
    lv_obj_set_width(ui_PanelMotor, 160);
    lv_obj_set_height(ui_PanelMotor, 77);
    lv_obj_set_x(ui_PanelMotor, 46);
    lv_obj_set_y(ui_PanelMotor, 161);
    lv_obj_set_align(ui_PanelMotor, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelMotor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelMotor, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PanelMotor, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelMotor, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelMotor, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_PanelMotor, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_Label_MotorTemp = lv_label_create(ui_PanelMotor);
    lv_obj_set_width(ui_Label_MotorTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_MotorTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_MotorTemp, 29);
    lv_obj_set_y(ui_Label_MotorTemp, 2);
    lv_obj_set_align(ui_Label_MotorTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_MotorTemp, "22°C");
    ui_object_set_themeable_style_property(ui_Label_MotorTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_MotorTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_MotorTemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_MotorTemp, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_SRInfo);
    lv_img_set_src(ui_Image2, &ui_img_secondride_diagnose_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 466
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 466
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Image2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Image2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ForeColor);
    ui_object_set_themeable_style_property(ui_Image2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Image2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_Panel_ChargerON = lv_obj_create(ui_SRInfo);
    lv_obj_set_width(ui_Panel_ChargerON, 39);
    lv_obj_set_height(ui_Panel_ChargerON, 62);
    lv_obj_set_x(ui_Panel_ChargerON, -169);
    lv_obj_set_y(ui_Panel_ChargerON, -3);
    lv_obj_set_align(ui_Panel_ChargerON, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_ChargerON, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_ChargerON, lv_color_hex(0x00A1EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_ChargerON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_ChargePower = lv_label_create(ui_SRInfo);
    lv_obj_set_width(ui_Label_ChargePower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_ChargePower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_ChargePower, -172);
    lv_obj_set_y(ui_Label_ChargePower, -55);
    lv_obj_set_align(ui_Label_ChargePower, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_ChargePower, "1000W");
    ui_object_set_themeable_style_property(ui_Label_ChargePower, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_ChargePower, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_ChargePower, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_ChargePower, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelVersion = lv_obj_create(ui_SRInfo);
    lv_obj_set_width(ui_PanelVersion, 164);
    lv_obj_set_height(ui_PanelVersion, 108);
    lv_obj_set_x(ui_PanelVersion, -122);
    lv_obj_set_y(ui_PanelVersion, 110);
    lv_obj_set_align(ui_PanelVersion, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelVersion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelVersion, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PanelVersion, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelVersion, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelVersion, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_PanelVersion, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_Label_SWversion = lv_label_create(ui_PanelVersion);
    lv_obj_set_width(ui_Label_SWversion, 150);
    lv_obj_set_height(ui_Label_SWversion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_SWversion, 23);
    lv_obj_set_y(ui_Label_SWversion, 0);
    lv_obj_set_align(ui_Label_SWversion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_SWversion, "SW:?.?.?");
    ui_object_set_themeable_style_property(ui_Label_SWversion, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_SWversion, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_SWversion, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_SWversion, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_HWversion = lv_label_create(ui_PanelVersion);
    lv_obj_set_width(ui_Label_HWversion, 134);
    lv_obj_set_height(ui_Label_HWversion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_HWversion, 15);
    lv_obj_set_y(ui_Label_HWversion, 30);
    lv_obj_set_align(ui_Label_HWversion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_HWversion, "HW:??");
    ui_object_set_themeable_style_property(ui_Label_HWversion, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_HWversion, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_HWversion, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_HWversion, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_DISPversion = lv_label_create(ui_PanelVersion);
    lv_obj_set_width(ui_Label_DISPversion, 150);
    lv_obj_set_height(ui_Label_DISPversion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_DISPversion, 2);
    lv_obj_set_y(ui_Label_DISPversion, -30);
    lv_obj_set_align(ui_Label_DISPversion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_DISPversion, "DISP:?.?.?");
    ui_object_set_themeable_style_property(ui_Label_DISPversion, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_DISPversion, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_DISPversion, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_DISPversion, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDistance = lv_obj_create(ui_SRInfo);
    lv_obj_set_width(ui_PanelDistance, 217);
    lv_obj_set_height(ui_PanelDistance, 70);
    lv_obj_set_x(ui_PanelDistance, 114);
    lv_obj_set_y(ui_PanelDistance, 83);
    lv_obj_set_align(ui_PanelDistance, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDistance, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelDistance, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PanelDistance, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelDistance, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelDistance, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_PanelDistance, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_Label_totalDistance = lv_label_create(ui_PanelDistance);
    lv_obj_set_width(ui_Label_totalDistance, 136);
    lv_obj_set_height(ui_Label_totalDistance, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_totalDistance, 8);
    lv_obj_set_y(ui_Label_totalDistance, -16);
    lv_obj_set_align(ui_Label_totalDistance, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_totalDistance, "999999");
    ui_object_set_themeable_style_property(ui_Label_totalDistance, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_totalDistance, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_totalDistance, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_totalDistance, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_tripDistance = lv_label_create(ui_PanelDistance);
    lv_obj_set_width(ui_Label_tripDistance, 120);
    lv_obj_set_height(ui_Label_tripDistance, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_tripDistance, -6);
    lv_obj_set_y(ui_Label_tripDistance, 16);
    lv_obj_set_align(ui_Label_tripDistance, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_tripDistance, "99999");
    ui_object_set_themeable_style_property(ui_Label_tripDistance, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_tripDistance, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_tripDistance, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_tripDistance, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_km = lv_label_create(ui_PanelDistance);
    lv_obj_set_width(ui_Label_km, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_km, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_km, 91);
    lv_obj_set_y(ui_Label_km, -14);
    lv_obj_set_align(ui_Label_km, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_km, "km");
    ui_object_set_themeable_style_property(ui_Label_km, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_km, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_km, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_km, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_km1 = lv_label_create(ui_PanelDistance);
    lv_obj_set_width(ui_Label_km1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_km1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_km1, 69);
    lv_obj_set_y(ui_Label_km1, 19);
    lv_obj_set_align(ui_Label_km1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_km1, "km");
    ui_object_set_themeable_style_property(ui_Label_km1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_km1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_km1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_km1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_trip = lv_label_create(ui_PanelDistance);
    lv_obj_set_width(ui_Label_trip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_trip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_trip, -74);
    lv_obj_set_y(ui_Label_trip, 17);
    lv_obj_set_align(ui_Label_trip, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_trip, "trip:");
    ui_object_set_themeable_style_property(ui_Label_trip, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_trip, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_font(ui_Label_trip, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_trip1 = lv_label_create(ui_PanelDistance);
    lv_obj_set_width(ui_Label_trip1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_trip1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_trip1, -79);
    lv_obj_set_y(ui_Label_trip1, -14);
    lv_obj_set_align(ui_Label_trip1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_trip1, "total:");
    ui_object_set_themeable_style_property(ui_Label_trip1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_trip1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_font(ui_Label_trip1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SRInfo, ui_event_SRInfo, LV_EVENT_ALL, NULL);
    uic_PanelConverter = ui_PanelConverter;
    uic_Label_CtrlTemp = ui_Label_CtrlTemp;
    uic_Label_limitSoC = ui_Label_limitSoC;
    uic_Label_limitTemp = ui_Label_limitTemp;
    uic_PanelBatt = ui_PanelBatt;
    uic_Label_BattVoltage = ui_Label_BattVoltage;
    uic_Label_BattCurrent = ui_Label_BattCurrent;
    uic_Label_BattMinTemp = ui_Label_BattMinTemp;
    uic_Label_BattMaxTemp = ui_Label_BattMaxTemp;
    uic_Slider_Batterie = ui_Slider_Batterie;
    uic_Label_MotorTemp = ui_Label_MotorTemp;
    uic_Panel_ChargerON = ui_Panel_ChargerON;
    uic_Label_ChargePower = ui_Label_ChargePower;
    uic_PanelVersion = ui_PanelVersion;
    uic_Label_SWversion = ui_Label_SWversion;
    uic_Label_HWversion = ui_Label_HWversion;
    uic_Label_DISPversion = ui_Label_DISPversion;
    uic_PanelDistance = ui_PanelDistance;
    uic_Label_totalDistance = ui_Label_totalDistance;
    uic_Label_tripDistance = ui_Label_tripDistance;
    uic_Label_km = ui_Label_km;
    uic_Label_trip = ui_Label_trip;

}
