// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SR_SoC-Display

#include "ui.h"

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Settings, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackColor);
    ui_object_set_themeable_style_property(ui_Settings, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackColor);

    ui_PanelSteckdose = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_PanelSteckdose, 230);
    lv_obj_set_height(ui_PanelSteckdose, 120);
    lv_obj_set_x(ui_PanelSteckdose, -50);
    lv_obj_set_y(ui_PanelSteckdose, -102);
    lv_obj_set_align(ui_PanelSteckdose, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSteckdose, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSteckdose, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PanelSteckdose, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelSteckdose, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelSteckdose, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_PanelSteckdose, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_Button_StartStop = lv_btn_create(ui_PanelSteckdose);
    lv_obj_set_width(ui_Button_StartStop, 192);
    lv_obj_set_height(ui_Button_StartStop, 70);
    lv_obj_set_x(ui_Button_StartStop, 0);
    lv_obj_set_y(ui_Button_StartStop, 14);
    lv_obj_set_align(ui_Button_StartStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button_StartStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_StartStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button_StartStop, lv_color_hex(0x20B24A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_StartStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_StartStop, &ui_img_602373867, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Button_StartStop, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Button_StartStop, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_ForeColor);

    ui_LabelSteckdose = lv_label_create(ui_PanelSteckdose);
    lv_obj_set_width(ui_LabelSteckdose, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSteckdose, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSteckdose, 1);
    lv_obj_set_y(ui_LabelSteckdose, -38);
    lv_obj_set_align(ui_LabelSteckdose, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSteckdose, "Steckdose");
    ui_object_set_themeable_style_property(ui_LabelSteckdose, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_LabelSteckdose, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_font(ui_LabelSteckdose, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAUS = lv_label_create(ui_PanelSteckdose);
    lv_obj_set_width(ui_LabelAUS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAUS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAUS, 58);
    lv_obj_set_y(ui_LabelAUS, 15);
    lv_obj_set_align(ui_LabelAUS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAUS, "AUS");
    ui_object_set_themeable_style_property(ui_LabelAUS, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_LabelAUS, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_LabelAUS, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAUS, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEIN = lv_label_create(ui_PanelSteckdose);
    lv_obj_set_width(ui_LabelEIN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEIN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEIN, -57);
    lv_obj_set_y(ui_LabelEIN, 14);
    lv_obj_set_align(ui_LabelEIN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEIN, "EIN");
    ui_object_set_themeable_style_property(ui_LabelEIN, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_LabelEIN, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_LabelEIN, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelEIN, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDarkmode = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_PanelDarkmode, 230);
    lv_obj_set_height(ui_PanelDarkmode, 135);
    lv_obj_set_x(ui_PanelDarkmode, -50);
    lv_obj_set_y(ui_PanelDarkmode, 102);
    lv_obj_set_align(ui_PanelDarkmode, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelDarkmode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelDarkmode, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PanelDarkmode, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelDarkmode, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelDarkmode, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_PanelDarkmode, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_SwitchDark = lv_switch_create(ui_PanelDarkmode);
    lv_obj_set_width(ui_SwitchDark, 171);
    lv_obj_set_height(ui_SwitchDark, 84);
    lv_obj_set_x(ui_SwitchDark, 0);
    lv_obj_set_y(ui_SwitchDark, 14);
    lv_obj_set_align(ui_SwitchDark, LV_ALIGN_CENTER);

    ui_LabelDarkmode = lv_label_create(ui_PanelDarkmode);
    lv_obj_set_width(ui_LabelDarkmode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDarkmode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDarkmode, 2);
    lv_obj_set_y(ui_LabelDarkmode, -48);
    lv_obj_set_align(ui_LabelDarkmode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDarkmode, "Anzeigefarben");
    ui_object_set_themeable_style_property(ui_LabelDarkmode, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_LabelDarkmode, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_font(ui_LabelDarkmode, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSoC = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_PanelSoC, 335);
    lv_obj_set_height(ui_PanelSoC, 63);
    lv_obj_set_x(ui_PanelSoC, -26);
    lv_obj_set_y(ui_PanelSoC, -4);
    lv_obj_set_align(ui_PanelSoC, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSoC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSoC, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PanelSoC, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelSoC, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelSoC, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_PanelSoC, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_LabelSoC = lv_label_create(ui_PanelSoC);
    lv_obj_set_width(ui_LabelSoC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSoC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSoC, -28);
    lv_obj_set_y(ui_LabelSoC, 0);
    lv_obj_set_align(ui_LabelSoC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSoC, "SoC Ladegrenze");
    ui_object_set_themeable_style_property(ui_LabelSoC, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_LabelSoC, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_LabelSoC, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSoC, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoCsetpoint = lv_roller_create(ui_Settings);
    lv_roller_set_options(ui_SoCsetpoint,
                          "5%\n10%\n15%\n20%\n25%\n30%\n35%\n40%\n45%\n50%\n55%\n60%\n65%\n70%\n75%\n80%\n85%\n90%\n95%\n100%",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_SoCsetpoint, 110);
    lv_obj_set_height(ui_SoCsetpoint, 277);
    lv_obj_set_x(ui_SoCsetpoint, 127);
    lv_obj_set_y(ui_SoCsetpoint, -5);
    lv_obj_set_align(ui_SoCsetpoint, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_SoCsetpoint, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_SoCsetpoint, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_font(ui_SoCsetpoint, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SoCsetpoint, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SoCsetpoint, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_PanelColor);
    ui_object_set_themeable_style_property(ui_SoCsetpoint, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_PanelColor);
    ui_object_set_themeable_style_property(ui_SoCsetpoint, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_SoCsetpoint, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_shadow_color(ui_SoCsetpoint, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SoCsetpoint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_SoCsetpoint, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_SoCsetpoint, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_font(ui_SoCsetpoint, &lv_font_montserrat_48, LV_PART_SELECTED | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SoCsetpoint, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_FrontScale);
    ui_object_set_themeable_style_property(ui_SoCsetpoint, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_FrontScale);

    lv_obj_add_event_cb(ui_Button_StartStop, ui_event_Button_StartStop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchDark, ui_event_SwitchDark, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings, ui_event_Settings, LV_EVENT_ALL, NULL);
    uic_Settings = ui_Settings;
    uic_PanelSteckdose = ui_PanelSteckdose;
    uic_Button_Start = ui_Button_StartStop;
    uic_LabelSteckdose = ui_LabelSteckdose;
    uic_LabelAUS = ui_LabelAUS;
    uic_LabelEIN = ui_LabelEIN;
    uic_PanelDarkmode = ui_PanelDarkmode;
    uic_SwitchDark = ui_SwitchDark;
    uic_PanelSoC = ui_PanelSoC;
    uic_LabelSoC = ui_LabelSoC;
    uic_SoCsetpoint = ui_SoCsetpoint;

}
