// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SR_SoC-Display

#include "ui.h"

void ui_Tacho_screen_init(void)
{
    ui_Tacho = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Tacho, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Tacho, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackColor);
    ui_object_set_themeable_style_property(ui_Tacho, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackColor);

    ui_Label_Time_2 = lv_label_create(ui_Tacho);
    lv_obj_set_width(ui_Label_Time_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Time_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Time_2, -105);
    lv_obj_set_y(ui_Label_Time_2, -1);
    lv_obj_set_align(ui_Label_Time_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Time_2, "00:00");
    ui_object_set_themeable_style_property(ui_Label_Time_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_Time_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_Time_2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Time_2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AkkuLogo_2 = lv_slider_create(ui_Tacho);
    lv_slider_set_range(ui_AkkuLogo_2, -5, 100);
    lv_slider_set_value(ui_AkkuLogo_2, 75, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_AkkuLogo_2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_AkkuLogo_2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_AkkuLogo_2, 96);
    lv_obj_set_height(ui_AkkuLogo_2, 140);
    lv_obj_set_x(ui_AkkuLogo_2, 39);
    lv_obj_set_y(ui_AkkuLogo_2, 109);
    lv_obj_set_align(ui_AkkuLogo_2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AkkuLogo_2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AkkuLogo_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AkkuLogo_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_AkkuLogo_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_AkkuLogo_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_AkkuLogo_2, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_AkkuLogo_2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AkkuLogo_2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AkkuLogo_2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_AkkuLogo_2, &ui_img_secondride_logows_bar_klein_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_AkkuLogo_2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AkkuLogo_2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Tacho);
    lv_img_set_src(ui_Image1, &ui_img_secondride_logows_klein_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 170
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 209
    lv_obj_set_x(ui_Image1, 2);
    lv_obj_set_y(ui_Image1, 109);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Image1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Image1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_Arc_Speed_2 = lv_arc_create(ui_Tacho);
    lv_obj_set_width(ui_Arc_Speed_2, 468);
    lv_obj_set_height(ui_Arc_Speed_2, 468);
    lv_obj_set_align(ui_Arc_Speed_2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc_Speed_2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_Arc_Speed_2, 0, 80);
    lv_arc_set_value(ui_Arc_Speed_2, 0);
    lv_arc_set_bg_angles(ui_Arc_Speed_2, 130, 50);
    ui_object_set_themeable_style_property(ui_Arc_Speed_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_BackScale);
    ui_object_set_themeable_style_property(ui_Arc_Speed_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_BackScale);
    lv_obj_set_style_arc_width(ui_Arc_Speed_2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc_Speed_2, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_Arc_Speed_2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_FrontScale);
    ui_object_set_themeable_style_property(ui_Arc_Speed_2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_FrontScale);
    lv_obj_set_style_arc_width(ui_Arc_Speed_2, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc_Speed_2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_Arc_Speed_2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Arc_Reku = lv_arc_create(ui_Tacho);
    lv_obj_set_width(ui_Arc_Reku, 468);
    lv_obj_set_height(ui_Arc_Reku, 468);
    lv_obj_set_x(ui_Arc_Reku, 0);
    lv_obj_set_y(ui_Arc_Reku, -1);
    lv_obj_set_align(ui_Arc_Reku, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc_Reku, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_Arc_Reku, -100, 100);
    lv_arc_set_value(ui_Arc_Reku, -75);
    lv_arc_set_bg_angles(ui_Arc_Reku, 60, 120);
    lv_arc_set_mode(ui_Arc_Reku, LV_ARC_MODE_SYMMETRICAL);
    ui_object_set_themeable_style_property(ui_Arc_Reku, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_BackScale);
    ui_object_set_themeable_style_property(ui_Arc_Reku, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_BackScale);
    lv_obj_set_style_arc_width(ui_Arc_Reku, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc_Reku, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_Arc_Reku, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_FrontScale);
    ui_object_set_themeable_style_property(ui_Arc_Reku, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_FrontScale);
    lv_obj_set_style_arc_width(ui_Arc_Reku, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc_Reku, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_Arc_Reku, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ImageSkala = lv_img_create(ui_Tacho);
    lv_img_set_src(ui_ImageSkala, &ui_img_tachoskala_png);
    lv_obj_set_width(ui_ImageSkala, LV_SIZE_CONTENT);   /// 466
    lv_obj_set_height(ui_ImageSkala, LV_SIZE_CONTENT);    /// 466
    lv_obj_set_x(ui_ImageSkala, 0);
    lv_obj_set_y(ui_ImageSkala, -1);
    lv_obj_set_align(ui_ImageSkala, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSkala, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSkala, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ImageSkala, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_ImageSkala, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_Label_SoC_Value_2 = lv_label_create(ui_Tacho);
    lv_obj_set_width(ui_Label_SoC_Value_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_SoC_Value_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_SoC_Value_2, -257);
    lv_obj_set_y(ui_Label_SoC_Value_2, 176);
    lv_obj_set_align(ui_Label_SoC_Value_2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_SoC_Value_2, "100");
    ui_object_set_themeable_style_property(ui_Label_SoC_Value_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_SoC_Value_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_SoC_Value_2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_SoC_Value_2, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_SoC_Unit_2 = lv_label_create(ui_Tacho);
    lv_obj_set_width(ui_Label_SoC_Unit_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_SoC_Unit_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_SoC_Unit_2, -14);
    lv_obj_set_y(ui_Label_SoC_Unit_2, 176);
    lv_obj_set_align(ui_Label_SoC_Unit_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_SoC_Unit_2, "%");
    ui_object_set_themeable_style_property(ui_Label_SoC_Unit_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_SoC_Unit_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_font(ui_Label_SoC_Unit_2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_km_Value_2 = lv_label_create(ui_Tacho);
    lv_obj_set_width(ui_Label_km_Value_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_km_Value_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_km_Value_2, -150);
    lv_obj_set_y(ui_Label_km_Value_2, 173);
    lv_obj_set_align(ui_Label_km_Value_2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_km_Value_2, "70");
    ui_object_set_themeable_style_property(ui_Label_km_Value_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_km_Value_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_km_Value_2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_km_Value_2, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_km_Unit_2 = lv_label_create(ui_Tacho);
    lv_obj_set_width(ui_Label_km_Unit_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_km_Unit_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_km_Unit_2, 105);
    lv_obj_set_y(ui_Label_km_Unit_2, 173);
    lv_obj_set_align(ui_Label_km_Unit_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_km_Unit_2, "km");
    ui_object_set_themeable_style_property(ui_Label_km_Unit_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_km_Unit_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_font(ui_Label_km_Unit_2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_BattTemp_Value2 = lv_label_create(ui_Tacho);
    lv_obj_set_width(ui_Label_BattTemp_Value2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_BattTemp_Value2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_BattTemp_Value2, -287);
    lv_obj_set_y(ui_Label_BattTemp_Value2, 95);
    lv_obj_set_align(ui_Label_BattTemp_Value2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label_BattTemp_Value2, "44°C");
    ui_object_set_themeable_style_property(ui_Label_BattTemp_Value2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_BattTemp_Value2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_BattTemp_Value2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_BattTemp_Value2, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label_BattTemp_Value2, lv_color_hex(0xEE8D00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label_BattTemp_Value2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_WLAN_2 = lv_img_create(ui_Tacho);
    lv_img_set_src(ui_Image_WLAN_2, &ui_img_1767220752);
    lv_obj_set_width(ui_Image_WLAN_2, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image_WLAN_2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image_WLAN_2, 133);
    lv_obj_set_y(ui_Image_WLAN_2, -101);
    lv_obj_set_align(ui_Image_WLAN_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_WLAN_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_WLAN_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image_WLAN_2, 180);
    ui_object_set_themeable_style_property(ui_Image_WLAN_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Image_WLAN_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_Image_Shelly_2 = lv_img_create(ui_Tacho);
    lv_img_set_src(ui_Image_Shelly_2, &ui_img_602373867);
    lv_obj_set_width(ui_Image_Shelly_2, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image_Shelly_2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image_Shelly_2, 136);
    lv_obj_set_y(ui_Image_Shelly_2, 87);
    lv_obj_set_align(ui_Image_Shelly_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Shelly_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Shelly_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image_Shelly_2, 180);
    ui_object_set_themeable_style_property(ui_Image_Shelly_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Image_Shelly_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_Image_Error_2 = lv_img_create(ui_Tacho);
    lv_img_set_src(ui_Image_Error_2, &ui_img_133863867);
    lv_obj_set_width(ui_Image_Error_2, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image_Error_2, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image_Error_2, 163);
    lv_obj_set_y(ui_Image_Error_2, 0);
    lv_obj_set_align(ui_Image_Error_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Error_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Error_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image_Error_2, 200);
    lv_obj_set_style_img_recolor(ui_Image_Error_2, lv_color_hex(0xFA0707), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image_Error_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_GO_2 = lv_img_create(ui_Tacho);
    lv_img_set_src(ui_Image_GO_2, &ui_img_1435283132);
    lv_obj_set_width(ui_Image_GO_2, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image_GO_2, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image_GO_2, 164);
    lv_obj_set_y(ui_Image_GO_2, 0);
    lv_obj_set_align(ui_Image_GO_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_GO_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_GO_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image_GO_2, 150);
    lv_obj_set_style_img_recolor(ui_Image_GO_2, lv_color_hex(0x055102), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image_GO_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_Brake_2 = lv_img_create(ui_Tacho);
    lv_img_set_src(ui_Image_Brake_2, &ui_img_400979676);
    lv_obj_set_width(ui_Image_Brake_2, LV_SIZE_CONTENT);   /// 65
    lv_obj_set_height(ui_Image_Brake_2, LV_SIZE_CONTENT);    /// 65
    lv_obj_set_x(ui_Image_Brake_2, 115);
    lv_obj_set_y(ui_Image_Brake_2, 0);
    lv_obj_set_align(ui_Image_Brake_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Brake_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Brake_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image_Brake_2, 180);
    lv_obj_set_style_img_recolor(ui_Image_Brake_2, lv_color_hex(0xEC7213), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image_Brake_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_HotSpot_2 = lv_img_create(ui_Tacho);
    lv_img_set_src(ui_Image_HotSpot_2, &ui_img_517647767);
    lv_obj_set_width(ui_Image_HotSpot_2, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image_HotSpot_2, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image_HotSpot_2, 134);
    lv_obj_set_y(ui_Image_HotSpot_2, -101);
    lv_obj_set_align(ui_Image_HotSpot_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_HotSpot_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_HotSpot_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image_HotSpot_2, 180);
    ui_object_set_themeable_style_property(ui_Image_HotSpot_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Image_HotSpot_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_Label_Speed_Value_2 = lv_label_create(ui_Tacho);
    lv_obj_set_width(ui_Label_Speed_Value_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Speed_Value_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Speed_Value_2, 0);
    lv_obj_set_y(ui_Label_Speed_Value_2, -87);
    lv_obj_set_align(ui_Label_Speed_Value_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Speed_Value_2, "66");
    ui_object_set_themeable_style_property(ui_Label_Speed_Value_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_Speed_Value_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_Speed_Value_2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Speed_Value_2, &ui_font_ArialBig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_kmh_Unit_2 = lv_label_create(ui_Tacho);
    lv_obj_set_width(ui_Label_kmh_Unit_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_kmh_Unit_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_kmh_Unit_2, 1);
    lv_obj_set_y(ui_Label_kmh_Unit_2, -25);
    lv_obj_set_align(ui_Label_kmh_Unit_2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_kmh_Unit_2, "km/h");
    ui_object_set_themeable_style_property(ui_Label_kmh_Unit_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_kmh_Unit_2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_font(ui_Label_kmh_Unit_2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Zeiger = lv_img_create(ui_Tacho);
    lv_img_set_src(ui_Zeiger, &ui_img_zeiger2_png);
    lv_obj_set_width(ui_Zeiger, LV_SIZE_CONTENT);   /// 6
    lv_obj_set_height(ui_Zeiger, LV_SIZE_CONTENT);    /// 220
    lv_obj_set_x(ui_Zeiger, 1);
    lv_obj_set_y(ui_Zeiger, 22);
    lv_obj_set_align(ui_Zeiger, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Zeiger, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Zeiger, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_Zeiger, 3, 220);
    lv_img_set_angle(ui_Zeiger, 1380);
    lv_obj_set_style_img_recolor(ui_Zeiger, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Zeiger, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image12 = lv_img_create(ui_Tacho);
    lv_img_set_src(ui_Image12, &ui_img_strich_kurz_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 4
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_Image12, 0);
    lv_obj_set_y(ui_Image12, 232);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Tacho);
    lv_obj_set_width(ui_Panel1, 40);
    lv_obj_set_height(ui_Panel1, 40);
    lv_obj_set_x(ui_Panel1, 1);
    lv_obj_set_y(ui_Panel1, 9);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFF0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_LoadPower_2 = lv_label_create(ui_Tacho);
    lv_obj_set_width(ui_Label_LoadPower_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_LoadPower_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_LoadPower_2, 30);
    lv_obj_set_y(ui_Label_LoadPower_2, -5);
    lv_obj_set_align(ui_Label_LoadPower_2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_LoadPower_2, "wird geladen mit 1000W");
    lv_obj_set_style_text_color(ui_Label_LoadPower_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_LoadPower_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_LoadPower_2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label_LoadPower_2, lv_color_hex(0x00A1EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label_LoadPower_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label_LoadPower_2, lv_color_hex(0x00A1EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label_LoadPower_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label_LoadPower_2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Threshold_2 = lv_label_create(ui_Tacho);
    lv_obj_set_width(ui_Label_Threshold_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Threshold_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Threshold_2, 30);
    lv_obj_set_y(ui_Label_Threshold_2, 30);
    lv_obj_set_align(ui_Label_Threshold_2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_Threshold_2, "bis 80%");
    lv_obj_set_style_text_color(ui_Label_Threshold_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Threshold_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Threshold_2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Threshold_2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label_Threshold_2, lv_color_hex(0x00A1EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label_Threshold_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label_Threshold_2, lv_color_hex(0x00A1EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label_Threshold_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label_Threshold_2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_LoadTempHigh2 = lv_label_create(ui_Tacho);
    lv_obj_set_width(ui_Label_LoadTempHigh2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_LoadTempHigh2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_LoadTempHigh2, 30);
    lv_obj_set_y(ui_Label_LoadTempHigh2, -40);
    lv_obj_set_align(ui_Label_LoadTempHigh2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label_LoadTempHigh2, "Akkutemperatur zu hoch");
    lv_obj_set_style_text_color(ui_Label_LoadTempHigh2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_LoadTempHigh2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_LoadTempHigh2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label_LoadTempHigh2, lv_color_hex(0xEE8C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label_LoadTempHigh2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label_LoadTempHigh2, lv_color_hex(0xEE8C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label_LoadTempHigh2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label_LoadTempHigh2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_Achtung2 = lv_img_create(ui_Tacho);
    lv_img_set_src(ui_Image_Achtung2, &ui_img_133863867);
    lv_obj_set_width(ui_Image_Achtung2, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image_Achtung2, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image_Achtung2, -105);
    lv_obj_set_y(ui_Image_Achtung2, -94);
    lv_obj_set_align(ui_Image_Achtung2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_Achtung2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_Achtung2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Image_Achtung2, lv_color_hex(0xEE8C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image_Achtung2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Tacho, ui_event_Tacho, LV_EVENT_ALL, NULL);
    uic_Tacho = ui_Tacho;
    uic_Label_Time_2 = ui_Label_Time_2;
    uic_AkkuLogo_2 = ui_AkkuLogo_2;
    uic_Arc_Speed_2 = ui_Arc_Speed_2;
    uic_Arc_Reku = ui_Arc_Reku;
    uic_ImageSkala = ui_ImageSkala;
    uic_Label_SoC_Value_2 = ui_Label_SoC_Value_2;
    uic_Label_SoC_Unit_2 = ui_Label_SoC_Unit_2;
    uic_Label_km_Value_2 = ui_Label_km_Value_2;
    uic_Label_km_Unit_2 = ui_Label_km_Unit_2;
    uic_Label_BattTemp_Value2 = ui_Label_BattTemp_Value2;
    uic_Image_WLAN_2 = ui_Image_WLAN_2;
    uic_Image_Shelly_2 = ui_Image_Shelly_2;
    uic_Image_Error_2 = ui_Image_Error_2;
    uic_Image_GO_2 = ui_Image_GO_2;
    uic_Image_Brake_2 = ui_Image_Brake_2;
    uic_Image_HotSpot_2 = ui_Image_HotSpot_2;
    uic_Label_Speed_Value_2 = ui_Label_Speed_Value_2;
    uic_Label_kmh_Unit_2 = ui_Label_kmh_Unit_2;
    uic_Zeiger = ui_Zeiger;
    uic_Label_LoadPower_2 = ui_Label_LoadPower_2;
    uic_Label_Threshold_2 = ui_Label_Threshold_2;
    uic_Label_LoadTempHigh2 = ui_Label_LoadTempHigh2;
    uic_Image_Achtung2 = ui_Image_Achtung2;

}
