// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SR_SoC-Display

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BACKCOLOR 0
#define UI_THEME_COLOR_FORECOLOR 1
#define UI_THEME_COLOR_BACKSCALE 2
#define UI_THEME_COLOR_FRONTSCALE 3
#define UI_THEME_COLOR_PANELCOLOR 4

#define UI_THEME_DEFAULT 0

#define UI_THEME_DARKMODE 1

  extern ui_theme_variable_t _ui_theme_color_BackColor[2];
  extern ui_theme_variable_t _ui_theme_alpha_BackColor[2];

  extern ui_theme_variable_t _ui_theme_color_ForeColor[2];
  extern ui_theme_variable_t _ui_theme_alpha_ForeColor[2];

  extern ui_theme_variable_t _ui_theme_color_BackScale[2];
  extern ui_theme_variable_t _ui_theme_alpha_BackScale[2];

  extern ui_theme_variable_t _ui_theme_color_FrontScale[2];
  extern ui_theme_variable_t _ui_theme_alpha_FrontScale[2];

  extern ui_theme_variable_t _ui_theme_color_PanelColor[2];
  extern ui_theme_variable_t _ui_theme_alpha_PanelColor[2];

  extern const uint32_t* ui_theme_colors[2];
  extern const uint8_t* ui_theme_alphas[2];
  extern uint8_t ui_theme_idx;

  void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
