// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SR_SoC-Display

#include "ui.h"

void ui_WiFiInfo_screen_init(void)
{
    ui_WiFiInfo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WiFiInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_WiFiInfo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackColor);
    ui_object_set_themeable_style_property(ui_WiFiInfo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackColor);

    ui_PanelWiFi = lv_obj_create(ui_WiFiInfo);
    lv_obj_set_width(ui_PanelWiFi, 400);
    lv_obj_set_height(ui_PanelWiFi, 175);
    lv_obj_set_x(ui_PanelWiFi, 0);
    lv_obj_set_y(ui_PanelWiFi, -149);
    lv_obj_set_align(ui_PanelWiFi, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelWiFi, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PanelWiFi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelWiFi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelWiFi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_PanelWiFi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_Label_WiFi1 = lv_label_create(ui_PanelWiFi);
    lv_obj_set_width(ui_Label_WiFi1, 327);
    lv_obj_set_height(ui_Label_WiFi1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_WiFi1, 1);
    lv_obj_set_y(ui_Label_WiFi1, 2);
    lv_obj_set_align(ui_Label_WiFi1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label_WiFi1, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label_WiFi1, "Wifi-Info Zeile 1");
    lv_obj_set_scrollbar_mode(ui_Label_WiFi1, LV_SCROLLBAR_MODE_ON);
    ui_object_set_themeable_style_property(ui_Label_WiFi1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_WiFi1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_WiFi1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_WiFi1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_WiFi2 = lv_label_create(ui_PanelWiFi);
    lv_obj_set_width(ui_Label_WiFi2, 384);
    lv_obj_set_height(ui_Label_WiFi2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_WiFi2, 1);
    lv_obj_set_y(ui_Label_WiFi2, 35);
    lv_obj_set_align(ui_Label_WiFi2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label_WiFi2, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label_WiFi2, "Wifi-Info Zeile 2");
    lv_obj_set_scrollbar_mode(ui_Label_WiFi2, LV_SCROLLBAR_MODE_ON);
    ui_object_set_themeable_style_property(ui_Label_WiFi2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_WiFi2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_WiFi2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_WiFi2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_WiFi3 = lv_label_create(ui_PanelWiFi);
    lv_obj_set_width(ui_Label_WiFi3, 400);
    lv_obj_set_height(ui_Label_WiFi3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_WiFi3, 0);
    lv_obj_set_y(ui_Label_WiFi3, 67);
    lv_obj_set_align(ui_Label_WiFi3, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label_WiFi3, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label_WiFi3, "Wifi-Info Zeile 3");
    lv_obj_set_scrollbar_mode(ui_Label_WiFi3, LV_SCROLLBAR_MODE_ON);
    ui_object_set_themeable_style_property(ui_Label_WiFi3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_WiFi3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_WiFi3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_WiFi3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWifi = lv_img_create(ui_PanelWiFi);
    lv_img_set_src(ui_ImageWifi, &ui_img_374202920);
    lv_obj_set_width(ui_ImageWifi, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_ImageWifi, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_ImageWifi, 1);
    lv_obj_set_y(ui_ImageWifi, -50);
    lv_obj_set_align(ui_ImageWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWifi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ImageWifi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_ImageWifi, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_PanelShelly = lv_obj_create(ui_WiFiInfo);
    lv_obj_set_width(ui_PanelShelly, 400);
    lv_obj_set_height(ui_PanelShelly, 113);
    lv_obj_set_x(ui_PanelShelly, 2);
    lv_obj_set_y(ui_PanelShelly, 0);
    lv_obj_set_align(ui_PanelShelly, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelShelly, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelShelly, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PanelShelly, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelShelly, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelShelly, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_PanelShelly, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_Label_Shelly1 = lv_label_create(ui_PanelShelly);
    lv_obj_set_width(ui_Label_Shelly1, 400);
    lv_obj_set_height(ui_Label_Shelly1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Shelly1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label_Shelly1, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label_Shelly1, "Shelly-Info Zeile 1");
    lv_obj_set_scrollbar_mode(ui_Label_Shelly1, LV_SCROLLBAR_MODE_ON);
    ui_object_set_themeable_style_property(ui_Label_Shelly1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_Shelly1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_Shelly1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Shelly1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Shelly2 = lv_label_create(ui_PanelShelly);
    lv_obj_set_width(ui_Label_Shelly2, 400);
    lv_obj_set_height(ui_Label_Shelly2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Shelly2, 0);
    lv_obj_set_y(ui_Label_Shelly2, 30);
    lv_obj_set_align(ui_Label_Shelly2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label_Shelly2, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Label_Shelly2, "Shelly-Info Zeile 2");
    lv_obj_set_scrollbar_mode(ui_Label_Shelly2, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_Label_Shelly2, LV_DIR_LEFT);
    ui_object_set_themeable_style_property(ui_Label_Shelly2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_Shelly2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_Shelly2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Shelly2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageShelly = lv_img_create(ui_PanelShelly);
    lv_img_set_src(ui_ImageShelly, &ui_img_798314644);
    lv_obj_set_width(ui_ImageShelly, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_ImageShelly, LV_SIZE_CONTENT);    /// 222
    lv_obj_set_x(ui_ImageShelly, 0);
    lv_obj_set_y(ui_ImageShelly, -30);
    lv_obj_set_align(ui_ImageShelly, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageShelly, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageShelly, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageShelly, 350);
    ui_object_set_themeable_style_property(ui_ImageShelly, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_ImageShelly, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_PanelMQTT = lv_obj_create(ui_WiFiInfo);
    lv_obj_set_width(ui_PanelMQTT, 400);
    lv_obj_set_height(ui_PanelMQTT, 178);
    lv_obj_set_x(ui_PanelMQTT, 0);
    lv_obj_set_y(ui_PanelMQTT, 153);
    lv_obj_set_align(ui_PanelMQTT, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelMQTT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelMQTT, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_PanelMQTT, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelMQTT, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_PanelColor);
    ui_object_set_themeable_style_property(ui_PanelMQTT, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_PanelMQTT, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_ForeColor);

    ui_Label_MQTT1 = lv_label_create(ui_PanelMQTT);
    lv_obj_set_width(ui_Label_MQTT1, 400);
    lv_obj_set_height(ui_Label_MQTT1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_MQTT1, 0);
    lv_obj_set_y(ui_Label_MQTT1, -40);
    lv_obj_set_align(ui_Label_MQTT1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label_MQTT1, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label_MQTT1, "MQTT-Info Zeile 1");
    lv_obj_set_scrollbar_mode(ui_Label_MQTT1, LV_SCROLLBAR_MODE_ON);
    ui_object_set_themeable_style_property(ui_Label_MQTT1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_MQTT1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_MQTT1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_MQTT1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_MQTT2 = lv_label_create(ui_PanelMQTT);
    lv_obj_set_width(ui_Label_MQTT2, 332);
    lv_obj_set_height(ui_Label_MQTT2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_MQTT2, 0);
    lv_obj_set_y(ui_Label_MQTT2, -10);
    lv_obj_set_align(ui_Label_MQTT2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label_MQTT2, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Label_MQTT2, "MQTT-Info Zeile 2");
    lv_obj_set_scrollbar_mode(ui_Label_MQTT2, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_Label_MQTT2, LV_DIR_LEFT);
    ui_object_set_themeable_style_property(ui_Label_MQTT2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_ForeColor);
    ui_object_set_themeable_style_property(ui_Label_MQTT2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_ForeColor);
    lv_obj_set_style_text_align(ui_Label_MQTT2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_MQTT2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageMQTT = lv_img_create(ui_PanelMQTT);
    lv_img_set_src(ui_ImageMQTT, &ui_img_1045174431);
    lv_obj_set_width(ui_ImageMQTT, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_ImageMQTT, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_ImageMQTT, -5);
    lv_obj_set_y(ui_ImageMQTT, -70);
    lv_obj_set_align(ui_ImageMQTT, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageMQTT, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageMQTT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_WiFiInfo, ui_event_WiFiInfo, LV_EVENT_ALL, NULL);
    uic_WiFiInfo = ui_WiFiInfo;
    uic_PanelWiFi = ui_PanelWiFi;
    uic_Label_WiFi1 = ui_Label_WiFi1;
    uic_Label_WiFi2 = ui_Label_WiFi2;
    uic_Label_WiFi3 = ui_Label_WiFi3;
    uic_ImageWifi = ui_ImageWifi;
    uic_Label_Shelly1 = ui_Label_Shelly1;
    uic_Label_Shelly2 = ui_Label_Shelly2;
    uic_ImageShelly = ui_ImageShelly;
    uic_Label_MQTT1 = ui_Label_MQTT1;
    uic_Label_MQTT2 = ui_Label_MQTT2;
    uic_ImageMQTT = ui_ImageMQTT;

}
